FDTN-1016:Migrate to common charts
flowcommerce/location pull request #449
Opened 2022-06-20 07:26 UTC by himanshuupadhyay101

```diff
production, location, Service (v1) has changed:
- # Source: location/templates/service.yaml
+ # Source: flow-generic/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: location
    labels:
-     helm.sh/chart: location-0.0.1
+     helm.sh/chart: flow-generic-1.3.5
      app.kubernetes.io/instance: location
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: location
      app: location
  spec:
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
-     
    selector:
      app.kubernetes.io/name: location
      app.kubernetes.io/instance: location
production, location-flow-io, Gateway (networking.istio.io) has changed:
- # Source: location/templates/ingress.yaml
+ # Source: flow-generic/templates/ingress-defaults.yaml
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: location-flow-io
    labels:
      app.kubernetes.io/name: location
-     helm.sh/chart: location-0.0.1
+     helm.sh/chart: flow-generic-1.3.5
      app.kubernetes.io/instance: location
      app.kubernetes.io/managed-by: Tiller
      app: location
    annotations:
      kubernetes.io/ingress.class: "ingressgateway"
      kubernetes.io/ingress.tld: "api.flow.io"
      external-dns.alpha.kubernetes.io/ttl: "120"
  spec:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP2
        hosts:
-         - "location.api.flow.io"
+         - location.api.flow.io
        tls:
          httpsRedirect: true
      - port:
          number: 443
          name: https
          protocol: HTTP2
        hosts:
-         - "location.api.flow.io"
+         - location.api.flow.io
production, location-flow-pub, Gateway (networking.istio.io) has changed:
- # Source: location/templates/ingress.yaml
+ # Source: flow-generic/templates/ingress-defaults.yaml
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
  metadata:
    name: location-flow-pub
    labels:
      app.kubernetes.io/name: location
-     helm.sh/chart: location-0.0.1
+     helm.sh/chart: flow-generic-1.3.5
      app.kubernetes.io/instance: location
      app.kubernetes.io/managed-by: Tiller
      app: location
    annotations:
      kubernetes.io/ingress.class: "ingressgateway"
      kubernetes.io/ingress.tld: "flo.pub"
      external-dns.alpha.kubernetes.io/ttl: "120"
  spec:
    selector:
      istio: ingressgateway
    servers:
      - port:
          number: 80
          name: http
          protocol: HTTP2
        hosts:
-         - "location.flo.pub"
+         - location.flo.pub
        tls:
          httpsRedirect: true
      - port:
          number: 443
          name: https
          protocol: HTTP2
        hosts:
-         - "location.flo.pub"
+         - location.flo.pub
production, location-live, Deployment (apps) has changed:
- # Source: location/templates/deployment.yaml
+ # Source: flow-generic/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: location-live
    labels:
-     helm.sh/chart: location-0.0.1
+     helm.sh/chart: flow-generic-1.3.5
      app.kubernetes.io/instance: location
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: location
      app: location
      app.kubernetes.io/stage: live
-     flow.io/version: 0.7.83
+     flow.io/version: 0.7.83-1-gf114180
+     flow.io/team: core
  spec:
    replicas: 3
+   
    selector:
      matchLabels:
        app.kubernetes.io/name: location
        app.kubernetes.io/instance: location
        app.kubernetes.io/stage: live
    template:
      metadata:
        labels:
          app.kubernetes.io/name: location
          app.kubernetes.io/instance: location
          app.kubernetes.io/stage: live
          app: location
-         flow.io/version: 0.7.83
+         flow.io/version: 0.7.83-1-gf114180
+         flow.io/team: core
        annotations:
          iam.amazonaws.com/role: arn:aws:iam::479720515435:role/ecsInstanceRole
          sumologic.com/sourceCategory: location
+         sidecar.istio.io/logLevel: info
+         proxy.istio.io/config: '{"terminationDrainDuration": 30s}'
      spec:
+       terminationGracePeriodSeconds: 60
        containers:
          - name: location
-           image: "flowcommerce/location:0.7.83"
+           image: "flowcommerce/location:0.7.83-1-gf114180"
            imagePullPolicy: IfNotPresent
            env:
              - name: JAVA_OPTS
                value: "-Xms6100m -Xmx6100m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt -XX:+UseG1GC -XX:+UseStringDeduplication"
              - name: FLOW_KUBERNETES_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: FLOW_KUBERNETES_NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: FLOW_KUBERNETES_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: FLOW_KUBERNETES_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: FLOW_KUBERNETES_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: FLOW_KUBERNETES_POD_UID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.uid
-             - name: DD_AGENT_HOST
-               valueFrom:
-                 fieldRef:
-                   fieldPath: status.hostIP
              - name: DD_SERVICE
                value: location
              - name: DD_ENV
                value: live
              - name: DD_VERSION
-               value: 0.7.83
+               value: 0.7.83-1-gf114180
              - name: DD_JMXFETCH_STATSD_HOST
                value: 'unix:///var/run/datadog/dsd.socket'
              - name: DD_SERVICE_MAPPING
                value: postgresql:location-postgresql,java-aws-sdk:location-aws-sdk"
            args: ["production"]
            ports:
              - name: http
                containerPort: 9000
                protocol: TCP
            volumeMounts:
              - name: dsdsocket
                mountPath: /var/run/datadog
            startupProbe:
              httpGet:
                path: /_internal_/healthcheck
                port: http
              failureThreshold: 30
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /_internal_/healthcheck
                port: http
              failureThreshold: 6
              periodSeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /_internal_/healthcheck
                port: http
              failureThreshold: 3
              periodSeconds: 10
              timeoutSeconds: 5
            resources:
              limits:
                cpu: 1
                memory: 7100Mi
              requests:
                cpu: 1
                memory: 7100Mi
              
        imagePullSecrets:
          - name: flow-docker-hub
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - location
                topologyKey: topology.kubernetes.io/zone
        dnsConfig:
          options:
            - name: ndots
              value: "1"
        volumes:
          - name: dsdsocket
            hostPath:
              path: /var/run/datadog/
              type: DirectoryOrCreate
    strategy:
      type: RollingUpdate
production, location-live, DestinationRule (networking.istio. [...]

2022-06-20 08:25 UTC, gheine commented on Jenkinsfile
> +                new helmCommonDeploy().deploy('location', 'production', VERSION.printable(), 600)
no need to override the timeout value. Omit `, 600`

2022-06-20 08:25 UTC, gheine requested changes
One minor nit

2022-06-20 10:16 UTC, himanshuupadhyay101 commented on Jenkinsfile
> +                new helmCommonDeploy().deploy('location', 'production', VERSION.printable(), 600)
done required changes

2022-06-21 14:43 UTC, gheine approved these changes

2022-06-22 04:57 UTC, merged