FDN-2397:upgrade scala v2.13.13 and sbt version upgrade & Scoverage
flowcommerce/location pull request #528
Opened 2024-05-24 17:16 UTC by abhidwivedi2701

In this PR we are upgrading scala version 2.13.13 and sbt as well as scoverage upgrade. For this we have to add type annotation in mentioned files:

 api/app/controllers/Addresses.scala
 api/app/controllers/CountryDefaults.scala
 api/app/controllers/Healthchecks.scala
 api/app/controllers/Timezones.scala
 api/test/utils/CollectionsSpec.scala
 api/test/utils/DigitalElementSpec.scala

2024-05-24 17:17 UTC, flow-tech commented
helm diff detected no changes for location

2024-05-27 10:24 UTC, gheine commented on api/test/utils/DigitalElementSpec.scala
> +    DigitalElementIndexRecord(rangeStart, rangeEnd, fieldDelimiter, bytes)
let's revisit this together...

2024-05-27 10:24 UTC, gheine requested changes
see above

2024-05-27 11:42 UTC, flow-tech commented
helm diff detected no changes for location

2024-05-27 11:44 UTC, flow-tech commented
Click here for code coverage report: https://jenkins.flo.pub/job/flowcommerce/job/location/job/PR-528/2/scoverage-report/

2024-05-27 12:30 UTC, merged